version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.3.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.3-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./templates:/etc/nginx/templates
      - certbot-etc:/etc/letsencrypt
    environment:
      - HOSTNAME=$WP_HOSTNAME

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email contact@${WP_HOSTNAME} --agree-tos --no-eff-email --staging -d ${WP_HOSTNAME} -d www.${WP_HOSTNAME}

volumes:
  certbot-etc:
  wordpress:
  dbdata:
