services:
  db:
    image: mysql:8.0
    hostname: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
        retries: 3
        timeout: 5s

  wordpress:
    depends_on: 
      db:
        condition: service_healthy
    image: wordpress:6.4.1-fpm-alpine
    hostname: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB
    volumes:
      - wordpress:/var/www/html

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.3-alpine
    hostname: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./templates:/etc/nginx/templates
      - certbot-etc:/etc/letsencrypt
    environment:
      - HOSTNAME=$WP_HOSTNAME

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    hostname: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email contact@${WP_HOSTNAME} --agree-tos --no-eff-email --staging -d ${WP_HOSTNAME} -d www.${WP_HOSTNAME}

volumes:
  certbot-etc:
  wordpress:
  dbdata:
